---
- name: create instance aws
  hosts: localhost
  tasks:
           - name: create security group
             ec2_group:
                     name: webserver
                     description: example firewall aws rules
                     region: us-east-1
                     rules:
                             - proto: tcp
                               from_port: 80
                               to_port: 80
                               cidr_ip: 0.0.0.0/0
                             - proto: tcp
                               from_port: 443
                               to_port: 443
                               cidr_ip: 0.0.0.0/0
                             - proto: tcp
                               from_port: 22
                               to_port: 22
                               cidr_ip: #Inserir IP_PUBLICO/32

           - name: create sshkey pair
             ec2_key:
                    name: devops
                    key_material: '#INSERIR_CHAVE_PUBLICA'


           - name: instance ec2 webserver
             ec2:
                    key_name: devops
                    instance_type: t2.micro
                    region: us-east-1
                    image: ami-5a809b25
                    wait: yes
                    group: webserver
                    count: 1
                    user_data: |
                               #!/bin/bash
                               sudo apt-get update
                               sudo apt-get install nginx -y
                               echo " Curso DevSecOps na 4linux" > /var/www/html/index.html

